# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  kernel_package = pkgs.linuxPackages_latest;
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
  };

  boot = {
    consoleLogLevel = 3;
    tmp = {
      useTmpfs = true;
      cleanOnBoot = true;
    };

    kernelModules = [
      "i915"
    ];

    initrd = {
      availableKernelModules = [
        "vmd"
        "ahci"
        "nvme"
        "sd_mod"
      ];
      # systemd.services.systemd-udevd.after = [ "systemd-modules-load.service" ];
      compressor = "cat";
      verbose = false;
    };

    loader = {
      systemd-boot.enable = true;
      systemd-boot.consoleMode = "auto";
      efi.canTouchEfiVariables = true;
      timeout = 0;
    };
    kernelPackages = kernel_package;

    extraModulePackages = [ config.hardware.nvidia.package ];

    kernelParams = [
      "slab_nomerge"
      "init_on_alloc=1"
      "init_on_free=1"
      "page_alloc.shuffle=1"

      "rd.systemd.show_status=false"
      "rd.udev.log_level=3"

      # "cgroup_no_v1=all"
      "systemd.unified_cgroup_hierarchy=yes"

      "preempt=full"

      # "mitigations=off"

      # "i915.enable_psr=0"
      "i915.enable_guc=3"
      "i915.lvds_downclock=1"

      "nmi_watchdog=0"
      "nowatchdog"

      "video=efifb:auto"

      "systemd.gpt_auto=no"
      "intel_iommu=on"
      "iommu=pt"
      "threadirqs"
      "random.trust_cpu=on"
      "rcutree.enable_rcu_lazy=1"

      "rootdelay=0"
      # "usbcore.autosuspend=-1"
      "max_ptes_none=4096"

      "modprobe.blacklist=nova_core,nova_drm,nouveau,nvidiafb"
      "nouveau.modeset=0"
    ];
    kernel.sysctl = {
      "vm.vfs_cache_pressure" = 50;
      "kernel.nmi_watchdog" = 0;
      "kernel.printk" = "3 3 3 3";
      "kernel.kexec_load_disabled" = 1;
      "fs.file-max" = 2097152;

      "kernel.split_lock_mitigate" = 0;

      # Congestion control (BBR is great on high BDP/long fat pipes; on LAN, cubic is fine)
      "net.ipv4.tcp_congestion_control" = "bbr";

      # Larger autotune buffers for high throughput links (don’t overdo on small RAM)

      # Recover from bad PMTUs
      "net.ipv4.tcp_mtu_probing" = 1;

      # Reduce head‑of‑line for unsent data; can lower latency on busy writers
      "net.ipv4.tcp_notsent_lowat" = 131072; # try 64k–256k; 0 means unlimited

      "net.ipv4.tcp_moderate_rcvbuf" = 1;
      "net.ipv4.tcp_fastopen" = 3;
      "net.core.default_qdisc" = "fq"; # or cake
      "vm.laptop_mode" = 5;

      "net.core.optmem_max" = 40960;
      "net.ipv4.tcp_synack_retries" = 5;
      "net.ipv4.ip_local_port_range" = "1024 65535";
      "net.ipv4.tcp_slow_start_after_idle" = 0;
      "net.ipv4.tcp_base_mss" = 1024;
      "net.ipv4.tcp_adv_win_scale" = -2;

      # Name: K4YT3X's Hardened & Optimized Linux Kernel Parameters

      "kernel.randomize_va_space" = 2;

      # controls the System Request debugging functionality of the kernel
      "kernel.sysrq" = 0;

      # controls whether core dumps will append the PID to the core filename
      # useful for debugging multi-threaded applications
      "kernel.core_uses_pid" = 1;

      # restrict access to kernel address
      # kernel pointers printed using %pK will be replaced with 0’s regardless of privileges
      "kernel.kptr_restrict" = 0;

      # Ptrace protection using Yama
      #   - 0 (classic): allows any process to trace any other process under the same UID
      #   - 1 (restricted): only a parent process can be debugged
      #   - 2 (admin-only): only admins can use ptrace (CAP_SYS_PTRACE capability required)
      #   - 3 (no attach): disables ptrace completely, reboot is required to re-enable ptrace
      # the general recommendation for this setting is:
      #   - if you do not need to debug programs, set it to 3
      #   - if you need to debug programs (e.g., GDB, LLDB, strace), set it to 1
      # setting it to 3 will also break LXC v6+ procfs emulation for unprivileged containers
      #   (see GitHub issue https://github.com/lxc/lxcfs/issues/636)
      "kernel.yama.ptrace_scope" = 3;

      # restrict kernel logs to root only
      "kernel.dmesg_restrict" = 1;

      # disable the loading of kernel modules
      # this can be used to prevent runtime insertion of malicious modules
      # could break the system if enabled within sysctl.conf
      # consider setting this manually after system is up
      # sudo sysctl -w kernel.modules_disabled=1
      #kernel.modules_disabled = 1

      # allow for more PIDs
      # this value can be up to:
      #   - 32768 (2^15) on a 32-bit system
      #   - 4194304 (2^22) on a 64-bit system

      # reboot machine after kernel panic
      #kernel.panic = 10

      # restrict perf subsystem usage
      # prevent unprivileged attackers from loading vulnerable line disciplines with the TIOCSETD ioctl
      "dev.tty.ldisc_autoload" = 0;

      # Disable ftrace debugging unless explicitly required
      "kernel.ftrace_enabled" = lib.mkDefault false;

      # Harden reverse-path filtering and martian logging
      "net.ipv4.conf.all.log_martians" = lib.mkDefault true;
      "net.ipv4.conf.all.rp_filter" = lib.mkDefault "1";
      "net.ipv4.conf.default.log_martians" = lib.mkDefault true;
      "net.ipv4.conf.default.rp_filter" = lib.mkDefault "1";

      # Block ICMP redirects by default
      "net.ipv4.conf.all.accept_redirects" = lib.mkDefault false;
      "net.ipv4.conf.all.secure_redirects" = lib.mkDefault false;
      "net.ipv4.conf.default.accept_redirects" = lib.mkDefault false;
      "net.ipv4.conf.default.secure_redirects" = lib.mkDefault false;
      "net.ipv6.conf.all.accept_redirects" = lib.mkDefault false;
      "net.ipv6.conf.default.accept_redirects" = lib.mkDefault false;

      # Refuse to emit ICMP redirects
      "net.ipv4.conf.all.send_redirects" = lib.mkDefault false;
      "net.ipv4.conf.default.send_redirects" = lib.mkDefault false;

      "net.ipv4.conf.all.accept_source_route" = 0;
      "net.ipv4.conf.default.accept_source_route" = 0;
      ########## File System ##########

      # disallow core dumping by SUID/SGID programs
      "fs.suid_dumpable" = 0;

      # protect the creation of hard links
      # one of the following conditions must be fulfilled
      #   - the user can only link to files that he or she owns
      #   - the user must first have read and write access to a file, that he/she wants to link to
      "fs.protected_hardlinks" = 1;

      # protect the creation of symbolic links
      # one of the following conditions must be fulfilled
      #   - the process following the symbolic link is the owner of the symbolic link
      #   - the owner of the directory is also the owner of the symbolic link
      "fs.protected_symlinks" = 1;

      # enable extended FIFO protection
      "fs.protected_fifos" = 2;

      # similar to protected_fifos, but it avoids writes to an attacker-controlled regular file
      "fs.protected_regular" = 2;

      ########## Networking ##########
    };

    # https://github.com/positron-solutions/derpconfig/blob/master/examples/kernel-clang.nix
    kernelPatches = [
      {
        name = "Rust Support";
        patch = null;
        features = {
          rust = true;
        };
      }
    ];

    extraModprobeConfig = ''
      # Keep Bluetooth coexistence disabled for better BT audio stability
      options iwlwifi bt_coex_active=0

      # Enable software crypto (helps BT coexistence sometimes)
      options iwlwifi swcrypto=1

      # Disable power saving on Wi-Fi module to reduce radio state changes that might disrupt BT
      options iwlwifi power_save=0

      # Disable Unscheduled Automatic Power Save Delivery (U-APSD) to improve BT audio stability
      options iwlwifi uapsd_disable=1

      # Disable D0i3 power state to avoid problematic power transitions
      options iwlwifi d0i3_disable=1

      # Set power scheme for performance (iwlmvm)
      options iwlmvm power_scheme=1
    '';
    blacklistedKernelModules = [
      "nova_core"
      "nova_drm"
      "nouveau"
      "nvidiafb"
      "kvm"
      "kvm_intel" # or kvm_amd
    ];
  };

  services.scx = {
    enable = true;
    package = pkgs.scx.rustscheds;
    scheduler = "scx_lavd";
    extraArgs = [ "--autopower" ];

  };

  systemd.settings.Manager = {
    DefaultTimeoutStopSec = "3s";
    DefaultTimeoutStartSec = "3s";
    DefaultLimitNOFILE = 524288;
    RebootWatchdogSec = "3s";
    RuntimeWatchdogSec = "3s";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b4ca0f25-3031-4663-b9ea-0819f305e5ef";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "noatime"
      "lazytime"
      "compress=zstd:3"
      "discard=async"
      "space_cache=v2"
      "commit=60"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/762A-A7F8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # nix.settings.system-features = [
  #   "big-parallel"
  #   "gccarch-x86-64-v4"
  # ];
  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.enableAllFirmware = lib.mkDefault true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
