{
    wayland.windowManager.hyprland.settings = {
    bind = [
      "$modifier,K,exec,list-keybinds"
      "ALT, Space, exec,rofi-launcher"
      "$modifier SHIFT,W,exec,web-search"
      "$modifier ALT,W,exec,wallsetter"
      "$modifier SHIFT,N,exec,swaync-client -rs"
      "$modifier,W,exec, zen"
      "$modifier,C,exec, code --ozone-platform=wayland"
      "$modifier,Y,exec,kitty -e yazi"
      "$modifier,N,exec,kitty -e nmtui"
      "$modifier SHIFT,M,exec,kitty -e cava"
      "$modifier,E,exec,emopicker9000"
      # # "$modifier,S,exec,screenshootin"
      # bind = $mainMod, PRINT, exec, hyprshot -m window
      # # Screenshot a monitor
      # bind = , PRINT, exec, hyprshot -m output
      # # Screenshot a region
      # bind = $shiftMod, PRINT, exec, hyprshot -m region
      "$modifier,S,exec,hyprshot -m window"
      "$modifier SHIFT,S,exec,hyprshot -m output"
      "$modifier ALT,S,exec,hyprshot -m region"

      "$modifier,D,exec,discordcanary"
      "$modifier,O,exec,obsidian --ozone-platform=wayland"
      "$modifier SHIFT,C,exec,hyprpicker -a"
      "$modifier,T,exec,pypr toggle term"
      "$modifier SHIFT,T,exec, kitty -e btop"
      "$modifier,M,exec,pavucontrol"
      "$modifier,Q,killactive,"
      "$modifier,P,pseudo,"
      "$modifier,V,exec, rofi -modi clipboard:/etc/nixos/home-manager/modules/scripts/cliphist -display-columns 2 -show clipboard -show-icons && wtype -p \"$(wl-paste)\""
      # "$modifier SHIFT,V,exec, code"
      "$modifier SHIFT,I,togglesplit,"
      "$modifier,F,fullscreen,"
      "$modifier SHIFT,F,togglefloating,"
      "$modifier ALT,F,workspaceopt, allfloat"
      # "$modifier SHIFT,C,exit,"

      "$modifier SHIFT,left,resizeactive, -10 0"
      "$modifier SHIFT,right,resizeactive, 10 0"
      "$modifier SHIFT,up,resizeactive, 0 -10"
      "$modifier SHIFT,down,resizeactive, 0 10"

      "$modifier,left,movewindow,l"
      "$modifier,right,movewindow,r"
      "$modifier,up,movewindow,u"
      "$modifier,down,movewindow,d"

      "$modifier SHIFT,h,movewindow,l"
      "$modifier SHIFT,l,movewindow,r"
      "$modifier SHIFT,k,movewindow,u"
      "$modifier SHIFT,j,movewindow,d"

      "$modifier ALT, left, swapwindow,l"
      "$modifier ALT, right, swapwindow,r"
      "$modifier ALT, up, swapwindow,u"
      "$modifier ALT, down, swapwindow,d"

      "$modifier ALT, 43, swapwindow,l"
      "$modifier ALT, 46, swapwindow,r"
      "$modifier ALT, 45, swapwindow,u"
      "$modifier ALT, 44, swapwindow,d"

      "$modifier,left,movefocus,l"
      "$modifier,right,movefocus,r"
      "$modifier,up,movefocus,u"
      "$modifier,down,movefocus,d"
      "$modifier,h,movefocus,l"
      "$modifier,l,movefocus,r"
      "$modifier,k,movefocus,u"
      "$modifier,j,movefocus,d"
      "$modifier,1,workspace,1"
      "$modifier,2,workspace,2"
      "$modifier,3,workspace,3"
      "$modifier,4,workspace,4"
      "$modifier,5,workspace,5"
      "$modifier,6,workspace,6"
      "$modifier,7,workspace,7"
      "$modifier,8,workspace,8"
      "$modifier,9,workspace,9"
      "$modifier,0,workspace,10"
      "$modifier SHIFT,SPACE,movetoworkspace,special"
      "$modifier,SPACE,togglespecialworkspace"
      "$modifier SHIFT,1,movetoworkspace,1"
      "$modifier SHIFT,2,movetoworkspace,2"
      "$modifier SHIFT,3,movetoworkspace,3"
      "$modifier SHIFT,4,movetoworkspace,4"
      "$modifier SHIFT,5,movetoworkspace,5"
      "$modifier SHIFT,6,movetoworkspace,6"
      "$modifier SHIFT,7,movetoworkspace,7"
      "$modifier SHIFT,8,movetoworkspace,8"
      "$modifier SHIFT,9,movetoworkspace,9"
      "$modifier SHIFT,0,movetoworkspace,10"
      "$modifier CONTROL,right,workspace,e+1"
      "$modifier CONTROL,left,workspace,e-1"
      "$modifier,mouse_down,workspace, e+1"
      "$modifier,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "$modifier, mouse:272, movewindow"
      "$modifier, mouse:273, resizewindow"
    ];
  };
}
